### ISSUE TITLE
Errors in installing mpi4py after OpenMPI

### ISSUE THREAD

**Issue by fsciortino** [apptainer/singularity#1689]
I'm having problems installing mpi4py in a container running Centos7 and including OpenMPI. I tried several methods (installing with yum and from source, for both OpenMPI and mpi4py), but I keep getting errors regarding undeclared OpenMPI variables.  

## Version of Singularity:
2.5.1

### Expected behavior
Complete installation of several packages, including OpenMPI and mpi4py. 

### Actual behavior
I installed OpenMPI following the method recommended at [http://singularity.lbl.gov/docs-recipes](url) and then installing mpi4py with yum, I get 
`Failed building wheel for mpi4py`
The installation then throws many errors complaining about missing MPI declarations, such as 
`src/mpi4py.MPI.c:69491:17: error: 'ompi_mpi_lb' undeclared (first use in this function)`
`src/mpi4py.MPI.c:76881:37: error: 'ompi_mpi_ub' undeclared (first use in this function)`

### Steps to reproduce behavior
Simplified recipe below. I include everything that could possibly give issues,  although I don't see any clear issues. 

```
BootStrap: docker
From: centos:latest

%environment
 export LC_ALL=C
 source /etc/profile
 
%setup
 # ensure that /etc/profile is sourced upon opening image
 mkdir -p $SINGULARITY_ROOTS/.singularity.d/env
 echo "source /etc/profile" >> $SINGULARITY_ROOTFS/.singularity.d/env/80-custom.sh
 echo "alias h='cd /home/sciortino'" >> $SINGULARITY_ROOTFS/.singularity.d/env/80-custom.sh
 echo "module purge" >> $SINGULARITY_ROOTFS/.singularity.d/env/80-custom.sh
 echo "source /codes_repo/fs_env/bin/activate" >> $SINGULARITY_ROOTFS/.singularity.d/env/80-custom.sh

 chmod u+x $SINGULARITY_ROOTFS/.singularity.d/env/80-custom.sh

%post
 yum -y update
 yum -y groupinstall 'Development Tools'
 yum -y install bind-utils
 yum -y install infiniband-diags
 yum -y install epel-release
 yum -y install vim
 yum -y install net-tools
 yum -y install nmap-ncat
 yum -y install telnet
 yum -y install wget
 yum -y install mlocate
 yum -y install curl file git 

 # Require python 2.7
 echo "Python version: "
 python -V

 yum -y install python-devel
 yum -y install python-pip
 yum -y install yum-utils
 yum -y install tkinter
 yum -y install lapack-devel lapack blas blas-devel
 yum -y install gcc gcc-c++ make 
 yum -y install cmake
 yum -y install emacs 
 yum -y install python-nlopt
 yum -y install libxml2 libxml2-devel libxslt libxslt-devel

# pip installations 
 pip install --upgrade pip
 pip install numpy==1.10.4
 pip install scipy==0.17.0
 pip install periodictable
 pip install emcee==2.1.0
 pip install sobol==0.9
 pip install -U setuptools wheel
 pip install 'ipython[all]==4.1.1'
 pip install scikit-image==0.12.3
 pip install pymysql
 pip install numdifftools==0.9.16
 python -mpip install -U matplotlib

# ----------- OpenMPI installation ------------
  git clone https://github.com/open-mpi/ompi.git
  cd ompi
   ./autogen.pl
   ./configure --prefix=/usr/local
   make
   make install

   /usr/local/bin/mpicc examples/ring_c.c -o /usr/bin/mpi_ring
   export PATH=${PATH}:/usr/local/openmpi/lib

   source /etc/profile
   yum -y install environment-modules
   source /etc/profile
 
   module list
   echo " "
   module avail # I don't see any modules here, although I'd expect to see mpi/openmpi-x86_64 or similar

  echo "###### Now installing mpi4py ########"
  env MPICC=/usr/local/openmpi/bin/mpicc pip install mpi4py
```

Thanks in advance for your help!

**Comment by jmstover** [comment]
Hi @fsciortino ,

  Those have been deprecated. On your OMPI configure add:
```
    --enable-mpi1-compatibility
```

  That should set the option that includes those deprecated defines.

*Edit:*
Note: You're building from the master branch which is going to be an OpenMPI 3.x version. Most likely mpi4py is targeting a 2.x version. The 3.x is _much_ better for Singularity, with the better PMIx and actual support in OpenMPI for the Singularity run time.

**Comment by fsciortino** [comment]
Thank you very much, @jmstover , for the quick answer. I did a few more tests based on your suggestions before writing back, but still no success. 

I tried to use 
 ./configure --prefix=/usr/local --enable-mpi1-compatibility
for the OpenMPI installation, but this crashes with an error that seems related to wrong Fortran versions (see error below).  Any ideas of how to solve this? 

Your edit also suggested to look into version compatibility between OMPI and mpi4py and I found these pages:
[https://bitbucket.org/mpi4py/mpi4py/issues/81/release-with-openmpi-30-support](url)
[https://scitas-data.epfl.ch/kb/MPI4PY](url)
These suggest using --no-chache-dir as an option in building mpi4py using pip with compatibility with OMPI 3.x. 

What is the standard way within Singularity to install OMPI+mpi4py? I don't see why these issues should be specific to my container.


```
make[2]: Entering directory `/ompi/ompi/mpi/fortran/use-mpi-tkr'
  PPFC     mpi.lo
pmpi-f90-removed-interfaces.h:25.26:
    Included at mpi.F90:69:

interface PMPI_Attr_delete
                          1
Error: Unexpected INTERFACE statement in INTERFACE block at (1)
pmpi-f90-removed-interfaces.h:115.53:
    Included at mpi.F90:69:

subroutine PMPI_Type_extent(datatype, extent, ierror)
                                                     1
Error: Symbol 'pmpi_type_extent' at (1) already has an explicit interface
pmpi-f90-removed-interfaces.h:116.33:
    Included at mpi.F90:69:

  integer, intent(in) :: datatype
                                 1
Error: Unexpected data declaration statement in INTERFACE block at (1)
pmpi-f90-removed-interfaces.h:117.32:
    Included at mpi.F90:69:

  integer, intent(out) :: extent
                                1
Error: Unexpected data declaration statement in INTERFACE block at (1)
pmpi-f90-removed-interfaces.h:118.32:
    Included at mpi.F90:69:

  integer, intent(out) :: ierror
                                1
Error: Unexpected data declaration statement in INTERFACE block at (1)
pmpi-f90-removed-interfaces.h:119.3:
    Included at mpi.F90:69:

end subroutine PMPI_Type_extent
   1
Error: Expecting END INTERFACE statement at (1)
pmpi-f90-removed-interfaces.h:31.31:
    Included at mpi.F90:69:

end subroutine PMPI_Attr_delete
                               1
Error: Ambiguous interfaces 'pmpi_attr_delete' and 'mpi_type_ub' in generic interface 'mpi_type_ub' at (1)
make[2]: *** [mpi.lo] Error 1
make[2]: Leaving directory `/ompi/ompi/mpi/fortran/use-mpi-tkr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/ompi/ompi'
make: *** [all-recursive] Error 1
ABORT: Aborting with RETVAL=255
```

**Comment by jmstover** [comment]
Not sure on that.  If you know you aren't going to need the Fortran bindings, you can run configure with:  `--disable-mpi-fortran` . That _should_ disable the building of the Fortran MPI bindings.

I can't find anything on a Fortran version (i.e. f77, f90, etc...) needed for building OpenMPI.  I would expect gfortran to "just work"... it usually defaults to `-std=gnu`. Maybe changing it to being `-std=f95` ... would make a difference. Do you know easily what the GCC/gfortran version from `centos:latest` is? 

> What is the standard way within Singularity to install OMPI+mpi4py?

Honestly, no idea. I had to look up what mpi4py was...  :/

*Edit:*
I don't know Fortran, but a quick scan over `ompi/mpi/fortran/use-mpi-tkr/mpi-f90-removed-interfaces.h` shows that it ends with:
```
interface MPI_Type_ub

subroutine MPI_Type_ub(datatype, ub, ierror)
  [...]
end subroutine MPI_Type_ub
```

It *does not* have a `end interface` closing statement. The next file included is the `pmpi-f90-removed-interfaces.h` file. And you're getting an error about:
```
Error: Unexpected INTERFACE statement in INTERFACE block at
```

So... after the configure, and *before* the make in your def file, add in:

```
echo "end interface" >> ompi/mpi/fortran/use-mpi-tkr/mpi-f90-removed-interfaces.h
```

It may just be that the current master is broke on the OpenMPI repo, because that file doesn't actually look right.

**Comment by fsciortino** [comment]
OK, I'm trying the edit that you suggested-- I'll post back here once I know how it goes. I'm also trying to install 
```
 yum -y install libxml2 libxml2-devel libxslt libxslt-devel gcc-gfortran
```
to make sure that all dependencies highlighted at [http://www.open-mpi.de/source/building.php](url) are resolved. Just to be clear: I do need Fortran bindings unfortunately. 

Anyway, if this is a problem related to the OpenMPI repo, I suspect that it would not be present in the version that is pulled by yum since this is more nicely packed up by the authors (or is this actually pulling from the same place?). I previously tried to install using "yum -y install openmpi openmpi-devel", but this was getting OpenMPI 1.x (or something similarly old), which is known not to work well with the process manager, so I had to abandon. However, if one were able to pull the 3.x OMPI version using yum, I think that all dependencies could be resolved and one could use a more thoroughly tested version. This idea isn't corroborated by much evidence, since I can't find a way to yum-pull a specific openmpi & openmpi-devel version.

**Comment by jmstover** [comment]
Hi @fsciortino,

  Yeah, the distro versions packaged are usually older. The file that you're erroring on is about a month old, it was added when they added the `--enable-mpi1-compatibility` option.

  FYI, I just build the master OMPI repo without error. My GCC version is 5.3.0 ... it may just be that version is more relaxed on syntax than the version you have.

I'm pretty sure you're getting the error because the file `mpi-f90-removed-interfaces.h` doesn't have the ending:

  `end interface`

  If you look at the other `.h` files in that directory, the ones similar to it do all end with that.

**Comment by fsciortino** [comment]
I agree that `end interface` is definitely missing. However, even after adding that line to `mpi-f90-removed-interfaces.h`, I still had an error related to missing variables. The key seems to be in the gcc version, as you suggested: I installed version 7 as suggested in one of the posts at [https://stackoverflow.com/questions/36327805/how-to-install-gcc-5-3-with-yum-on-centos-7-2](url) and it seems to work (I'm not calling this a victory yet since I haven't done enough testing, but it's at least compiling until the end).  

I also tried to install the latest gcc (v.8.1.0) using the following code (also from the link above), but it didn't work. If you have any suggestions about what I might be doing wrong here, it'd be interesting to find out. 

```
wget https://ftp.gnu.org/gnu/gcc/gcc-8.1.0/gcc-8.1.0.tar.gz
 tar -xzf gcc-8.1.0.tar.gz
 cd gcc-8.1.0/
 yum -y install libmpc-devel mpfr-devel gmp-devel
 yum -y install zlib-devel*
 ./configure --enable-multilib --with-system-zlib 
 make -j 8
 make install
```

Anyway, the following Singularity recipe now works: 

```
BootStrap: docker
From: centos:latest

%environment
 export LC_ALL=C
 source /etc/profile
 
%post
yum -y update
 yum -y groupinstall 'Development Tools'
 yum -y install bind-utils
 yum -y install infiniband-diags
 yum -y install epel-release
 yum -y install vim
 yum -y install net-tools
 yum -y install nmap-ncat
 yum -y install telnet
 yum -y install wget
 yum -y install mlocate
 yum -y install curl file git 

 # Require python 2.7
 echo "Python version: "
 python -V

 yum -y install python-devel
 yum -y install python-pip
 yum -y install yum-utils
 yum -y install tkinter
 yum -y install lapack-devel lapack blas blas-devel
 #yum -y install gcc

# Install recent gcc 
 yum -y install centos-release-scl
 yum -y install devtoolset-7-gcc*
 scl enable devtoolset-7 bash
 echo "gcc version: ************"
 which gcc
 gcc --version

 yum -y install cmake
 
# OpenMPI v.3.x compatibilty
 yum -y install m4 autoconf automake libtool flex

# Python pip installations (MITIM compatibility)
 pip install --upgrade pip

# ----------- OpenMPI installation ------------
 #yum -y install gcc gcc-c++ make gcc-gfortran
 yum -y install libxml2 libxml2-devel libxslt libxslt-devel

 echo "Installing OpenMPI into container..."

 # Here we are at the base, /, of the container
 git clone https://github.com/open-mpi/ompi.git

 # Now at /ompi
   cd ompi
   ./autogen.pl
   ./configure --prefix=/usr/local  --enable-mpi1-compatibility
    # as suggested on Github by jmstover:
   echo "end interface" >> ompi/mpi/fortran/use-mpi-tkr/mpi-f90-removed-interfaces.h
   make
   make install

   /usr/local/bin/mpicc examples/ring_c.c -o /usr/bin/mpi_ring
   export PATH=${PATH}:/usr/local/openmpi/lib
   
   source /etc/profile
   yum -y install environment-modules
   source /etc/profile
 
   module list
   echo " "
   module avail

  echo "###### Now installing mpi4py ########"
  env MPICC=/usr/local/openmpi/bin/mpicc pip install --no-cache-dir mpi4py
```

Hopefully, this sorts out all issues related to OMPI and mpi4py. Thank you very much for all your help!

**Comment by jmstover** [comment]
>  If you have any suggestions about what I might be doing wrong here, it'd be interesting to find out.

Nothing. My guess is it's just the version of Fortran used while coding, and the version of the compiler. Like I mentioned, GCC 5.3.0 built it w/ no errors, but it looks like CentOS 7 has 4.8.5 (and whatever backports they pull in).

For your 8.x compile, the only thing I see is you don't specify `--enable-languages`. If you want to keep testing that route, you can try changing to `./configure` to have:

    --enable-languages=c,c++,fortran

As long as they didn't modify default behavior between versions sometime, then the default is to build `all` languages.

**Comment by fsciortino** [comment]
According to [https://gcc.gnu.org/install/configure.html](url) , the default of configure in that case should be to build only a subset of languages which includes c,c++ and fortran, so I thought I could get by without specifying that command... but maybe there's more to the story. 

Unless you'd like to do it, I can open an issue on OpenMPI's repo, pointing out the missing `end interface` that you found.

**Comment by jmstover** [comment]
Hrmm... I looked through the `./configure` script for GCC 7.2.0 (have that source here), and it defaults to `all` if not given. I'm guessing that's referencing the 8.x release since that's the most recent.

And I did not open an issue on the OMPI repository.

**Comment by jsquyres** [comment]
We just fixed Open MPI's master to include the missing `end interface` (https://github.com/open-mpi/ompi/pull/5347).  Thanks for noticing and reporting!

FWIW: This `--enable-mpi1-compatiblity` CLI flag / functionality isn't in any released version yet; it will be in the upcoming Open MPI v4.0.0.

**Comment by jmstover** [comment]
@fsciortino,
Hrmmm...  It also may be worthwhile to change your OpenMPI build to being something like:

```
# Here we are at the base, /, of the container
git clone https://github.com/open-mpi/ompi.git
# Now at /ompi
cd ompi
# Change to 3.1.0 release (tag)
git checkout v3.1.0
./autogen.pl
./configure --prefix=/usr/local
make
make install
```

So, instead of building off the `master` branch, you grab the v3.1.0 release tag and build off that.

@jsquyres -- Thanks much.

**Comment by jsquyres** [comment]
@jmstover FYI: the tag is actually `v3.1.0` (note the prefix `v`).  Also note that v3.1.1 is immanent (possibly even this week?).

**Comment by jmstover** [comment]
Doh... skipped the leading `v` when in the `git tag` list. Thanks.

**Comment by fsciortino** [comment]
Unfortunately I'm still having some issues. The installation proceeds fine (I did install 3.1.0, since @jmstover wrote that it's much better than 2.1.0 in Singularity). However, I seem to still have problems in communication between the PMI and OMPI in host/local systems. Although I'm not seeing any obvious errors, when I move my container to a cluster all my mpi processes are ranked 0. 

Note that I do have installed the same OMPI version both on the host and in the container. I think that the problem I'm having is described at [http://singularity.lbl.gov/docs-hpc](url) as

> Using Open MPI 2.1 does not magically allow your container to connect to networking fabric libraries in the host. If your cluster has, for example, an infiniband network you still need to install OFED libraries into the container. Alternatively you could bind mount both Open MPI and networking libraries into the container, but this could run afoul of glib compatibility issues (its generally OK if the container glibc is more recent than the host, but not the other way around)

I'm guessing that the statement above applies to OMPI 2.1 as well as later versions. I'm not really experienced with OFED and networking libraries. Is it likely that I have to worry about those? Or is there something simpler that I'm overlooking? Any suggestions on how to proceed?
Thank you very much for your help!

**Comment by jmstover** [comment]
Hrmm... This is what I'm getting from a simple test:

```
$ salloc -n 64
$ generate_pbs_nodefile
/tmp/_5xpfQWfCm
$ mpiexec -n 64 -hostfile /tmp/_5xpfQWfCm \
    /share/apps/singularity-2.5.1/bin/singularity \
   exec \
   -B /opt/openmpi \
   ~/centos7.img ~/mpitest
Hello from proc compute-0-6.local, rank 10 of 64
Hello from proc compute-0-10.local, rank 45 of 64
Hello from proc compute-0-11.local, rank 48 of 64
Hello from proc compute-0-9.local, rank 33 of 64
  [ ... ]
Hello from proc compute-0-8.local, rank 25 of 64
Hello from proc compute-0-11.local, rank 58 of 64
Hello from proc compute-0-11.local, rank 53 of 64
Hello from proc compute-0-11.local, rank 59 of 64

$ mpiexec -V
mpiexec (OpenRTE) 2.1.1
```
This is a very specific setup though.

On all of the nodes, the same MPI is installed at `/opt/openmpi`. I created a CentOS 7 image, that's the same as the host, so I can bind the host MPI into the container w/o issue.

But, the simple MPI test is spread out across all the processes. The biggest thing is that the MPI on the host needs to be ABI compatible with the MPI in the container.

The PMIx stuff was designed to help work around some of the ABI compatibility issues.

**Comment by fsciortino** [comment]
Thanks @jmstover for your quick reply. I installed OMPI as a module on my cluster. This way, I am certain that I have the same version inside and outside the container. 

Key question: **why do you need to bind /opt/openmpi in your case?** Since I am loading OMPI as a personal module, should I do something similar? I git cloned the OMPI repo into my home directory (which is always mounted in the Singularity container), then installed in a separate directory to which I have write access (called /nobackup/users/MYUSERNAME, suppposed to be faster). I indicated the installation directory with "./configure --prefix=/nobackup/users/MYUSERNAME/my_directory_for_modules". I then mounted /nobackup/users/MYUSERNAME into my container. 

--- >Does that sound right? Assuming that your binding of /opt/openmpi was necessary, what I am doing should equivalent, since OMPI libraries and binaries should be all inside /nobackup/users/MYUSERNAME after OMPI installation. I have little experience with such installations, so I really appreciate your advice. 

Also, I noticed that the Centos7 releases on the cluster and in my container are slightly different:
- On cluster: CentOS Linux release 7.2.1511 (Core)
- In container: CentOS Linux release 7.5.1804 (Core) 
I'd be surprised if this made a difference, but I'm just mentioning in case...

**Comment by fsciortino** [comment]
Also, before using Singularity, I needed the following command (suggested by a more expert user) to run on my cluster:
`export I_MPI_FABRICS=shm:tcp`
which seems to specify to an Intel compiler what inter/intra-node communication protocol should be used. I found some info here: [https://scc.ustc.edu.cn/zlsc/tc4600/intel/2016.0.109/mpi/User_Guide/I_MPI_FABRICS.htm](url). 

My first thought was to include such export, since this is part of the Intel MPI Libraries (which I haven't dealt with directly and probably manage communication with the Kernel) and the installation procedure for OMPI doesn't say anything about them. I found that I do need to load a publicly-available Intel module (whose nature is unknown to me) on my cluster, otherwise I get an error regarding a missing libimf.so library. So, I'm loading such Intel module, keeping `export I_MPI_FABRICS=shm:tcp` and also using `export SINGULARITYENV_I_MPI_FABRICS=shm:tcp`, assuming that this would need to be exported in the container as well. I tried to exclude some of these options in several ways, but nothing seems to avoid my issue with all processes ranking 0. 

I'm writing these details although they might be quite specific to my cluster setup, hoping that some of this might make sense to you and you might spot what I'm doing wrong.

**Comment by jmstover** [comment]
Hi @fsciortino,

`I_MPI_FABRICS` is Intel MPI specific... If you're using Intel MPI, then throw everything out the window. If you are using OpenMPI, an equivalent setting CLI option is:  `-mca btl self,tcp`

Now... if you are using Intel MPI ... it again, theoretically should "just work."  You *might* need to bind mount your Intel MPI run time in.  For example, assuming it's installed at the default `/opt/intel/mpirt` ... then add in `-B /opt/intel/mpirt` to your singularity command line.

I also don't remember if hydra needed to be used or not (i.e. `mpiexec.hydra`) with Intel MPI.

> why do you need to bind /opt/openmpi in your case?

I did not have a MPI installed in the container, and instead used the host MPI since it was built for CentOS 7, and my image was CentOS 7. So, I was able to leverage the host MPI inside of the container, I just needed to bind mount in the host install location.

**Comment by fsciortino** [comment]
Hi @jmstover , 

Thank you very much for the clarification. My confusion arises from the fact that unless I load a module named "intel/2017-01" on my cluster I cannot get my OMPI module to work: a simple `mpiexec --version` returns `mpiexec: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or director` 
This seemed to suggest that some Intel machinery would always be needed to run on my cluster... Any ideas of why I would see this error related to libimf.so? There doesn't seem to be a file with this name anywhere in the directories where I installed OMPI...

I would prefer to use my own OMPI versions from beginning to end, to avoid relying too much on other people's installations. I tried adding the MCA command that you suggested (loading my own OMPI version, as well as the Intel module that defines the necessary libimf.so) , but this didn't seem to make any difference. With the command 
`mpiexec -np 10 -mca btl self,tcp singularity exec --cleanenv /nobackup/users/my_username/centos7ro_ompi310.img python /nobackup/users/my_username/test_MPI.py`
I still get all processes ranked 0.

**Comment by jmstover** [comment]
`libimf.so` -- This is a Intel library. Fortran IIRC.  If you're getting this on your OpenMPI run, then you had the Intel module loaded (or part of), and the Intel compiler was used. At least the Fortran compiler was used.

What's the output of: `ldd /path/to/your/mpiexec`  ... It could be the OpenMPI modules as well...

**Comment by fsciortino** [comment]
That seems to be right. The output of `ldd /path/to/my/mpiexec` is
```
linux-vdso.so.1 =>  (0x00007ffff7ffd000)
libopen-rte.so.40 => /nobackup1c/users/sciortino/sandbox/lib/libopen-rte.so.40 (0x00007ffff7d32000)
libopen-pal.so.40 => /nobackup1c/users/sciortino/sandbox/lib/libopen-pal.so.40 (0x00007ffff79fd000)
libm.so.6 => /usr/lib64/libm.so.6 (0x00007ffff76d5000)
libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00007ffff74c8000)
librt.so.1 => /usr/lib64/librt.so.1 (0x00007ffff72c0000)
libutil.so.1 => /usr/lib64/libutil.so.1 (0x00007ffff70bd000)
libz.so.1 => /usr/lib64/libz.so.1 (0x00007ffff6ea6000)
libgcc_s.so.1 => /home/software/gcc/6.2.0/lib64/libgcc_s.so.1 (0x00007ffff6c8f000)
libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007ffff6a73000)
libc.so.6 => /usr/lib64/libc.so.6 (0x00007ffff66b0000)
libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007ffff64ac000)
libimf.so => /home/software/intel/2017-01/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libimf.so (0x00007ffff5fc0000)
libsvml.so => /home/software/intel/2017-01/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libsvml.so (0x00007ffff50b4000)
libirng.so => /home/software/intel/2017-01/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libirng.so (0x00007ffff4d3f000)
libintlc.so.5 => /home/software/intel/2017-01/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00007ffff4ad5000)
/lib64/ld-linux-x86-64.so.2 (0x0000555555554000)

```
If I understand correctly, my mistake has been to install OpenMPI when the default compiler was the Intel one, although my container was built with gcc. When I built OMPI on the cluster, I actually had both a gcc-v.6.2.0 and an Intel-2017 compiler loaded as modules. From the output above, I suppose that one can infer that the Intel one was used. Does OMPI determine which compiler to use in these situations based on the order in which compilers were loaded (if there is more than one available)? 

So, it seems worth trying to unload the Intel compiler, load gcc-6.2.0 and create a new OMPI-v.3.1.0 module. I have gcc-v4.8.5 installed inside my container-- is the different version on the cluster likely to be a problem? 
Thanks so much for your help!

**Comment by jmstover** [comment]
> Does OMPI determine which compiler to use in these situations based on the order in which compilers were loaded

I'm wondering... if you load the Intel module, do you get get output with:  `echo $CC`

Generally, I would say no. But it seems like there is something getting set in the environment that's saying the compiler is `icc`/`icpc`

**Comment by fsciortino** [comment]
Yes, if I `module purge`, then `module load intel/2017-01`, using `echo $CC` returns `icc`. 

I tried to do as written above: unloading the Intel compiler, loading gcc-6.2.0 and creating a new OMPI-v.3.1.0 module. However, when I do `ldd /path/to/my/mpiexec`, I still get the same libraries as above, i.e. some of them being in /home/software/intel/2017-01/etcetc...

Is there a way to override those libraries when building OMPI, telling the compiler (which I'm now assuming is really gcc) to create a new version and let me point to that?
