### ISSUE TITLE
Consider making Plugin be an ordered structure

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#4112]
## Version of Singularity:

Current master branch, after merge of #3679

### Expected behavior

Plugins are processed in the order they are run

### Actual behavior

Plugins get a pseudo-random order, because the engine Plugin structure is a string map.  In PR #4108 which adds the --fusecmd, I worked around the issue by naming the plugins by number and changing the function that returns the list of plugins to sort them alphabetically.  I think it might be better to instead use an array, append new ones to the array, and refer to the plugins by number as the index.

Attention: @mem, @cclerget

**Comment by DrDaveD** [comment]
@mem, @cclerget, what do you think about this?

**Comment by cclerget** [comment]
Fixed by #4108

**Comment by mem** [comment]
I don't think I understand the issue.

Can you describe the problem without describing a solution along with it?

**Comment by DrDaveD** [comment]
The problem is that without the workaround in PR #4108 to [choose numbered plugin names](https://github.com/sylabs/singularity/pull/4108/files#diff-a55e54220196a0ff0d9fde854492aae7R106) and [sort them](https://github.com/sylabs/singularity/pull/4108/files#diff-a55e54220196a0ff0d9fde854492aae7R143), --fusemount options are not processed in the order in which they are given on the command line.  That's because plugin objects are given names and stored in an unordered data structure.  I don't see a good reason to name plugin objects instead of just referring to them by a number in the order in which they are created.

**Comment by mem** [comment]
Plugins are generic and the code goes out of its way to not assume anything regarding the structure of the plugin configuration. This is in part the reason why they are keyed by name. It is assumed that each plugin will have _one_ entry in the configuration. If the same plugin needs to handle multiple instances of whatever it does, it's up to the plugin to deal with that.

Part of the problem is that the FUSE support was meant to be a plugin with support from singularity but it isn't anymore, so there are some things which are awkward in the current implementation. Keep in mind that adding the --fusemount flag was rushed in.

Regarding this specific problem, I guess the fix that requires the least changes would be to add another field in FuseInfo structure, a sequential number, assigned in `GetPluginFuseMounts` and used in `GetPluginFuseMounts` as the key to sort on. This doesn't sound completely unreasonable since they could be multiple plugins handling fuse mounts (again, part of the problem is that there's no plugin and the implementation is half-tailored to the --fusemount flag) and there's no valid reason for them to fumble with their names to get things in a particular order.

The larger better fix is to deal with the fact that this is not handled by a plugin and simply extend the code to deal with fuse mounts as something that is part of singularity (move the FuseInfo structure from where it's hidden now to a more appropriate place among the other mount information). The plugin entry in the configuration can remain there in case future plugins need to store additional information related to the fuse mounts (or other mounts, or general plugin-related configuration).

The way I see it, there is an issue, but it's not the issue described here.

**Comment by DrDaveD** [comment]
I was not aware that the intention was to have one configuration entry per plugin, because there does not appear to be a way to have multiple FuseInfo structures from one plugin.

Even with that explanation I still don't understand the need or reason for naming plugins, but if you prefer to have an additional numeric field for sorting FuseInfo structures, that's fine with me.
I'm also OK with changing --fusemount to not be based on the plugin interface.  I tried to ask you and Cedric about that quite a while ago, but never got an answer.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by DrDaveD** [comment]
I'm not sure if this has been addressed or not but it's not important.  Closing.
