### ISSUE TITLE
think about non sudo ways to do a "sort of" bootstrap

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#572]
Given that a user wants to do operations on files, any of the following:

- add or remove files from a tar that will be added to the container
- add files from local host to container
- add files from web address to container

Given that we stay true to maintaining permissions (eg if the user can't do it outside of container, shouldn't be able to do it inside) we could have something that looks like a "non sudo" bootstrap, but the %post would be removed. Instead, we would just have `%files` `%labels` and `%environment`, like

```bash
Bootstrap: docker
From: ubuntu:latest

%files[add]
/local/file /path/in/container

%files[remove]
/path/in/container
```

We would just need a way to distinguish the context of the files command. In the example above, I'm using the similar approach that pip does when you install a particular version of a package, eg:

pip install package[tag]

We could also take a Dockerish approach, and just have ADD and REMOVE

```bash
Bootstrap: docker
From: ubuntu:latest

%files
ADD /local/file /path/in/container
REMOVE /path/in/container
```
 
which might make sense so the user can specify an ordering, and it fits with our current schema. We would want a user to be able to use the same bootstrap file for (with sudo) which would include `%post` and without sudo, which would not. Cool request by @satra ! Thoughts?

**Comment by satra** [comment]
thanks @vsoch - it seems like i can still do the following:

`singularity shell -c docker://some image`
go to a different terminal and make a copy of the rundir
modify the copy and use it as an image to singularity

so i'm not sure `%post` should be completely removed. in fact the command i ran was:

`find /path -name ".wh*" | xargs rm -f` 

that would be a rather long list of `REMOVE` commands :)

**Comment by vsoch** [comment]
hmm ok, we would need to figure out how to do this with in memory tars, meaning we aren't issuing commands to a file system, but we could do regular expressions over file name paths. Can you think of other commands that go beyond the scope of "find files that look like this and do something" that would be wanted in this kind of setting?

**Comment by satra** [comment]
ah i see. i could achieve the same through one of these options:

- allow adding scripts to `.singularity.d` folder (could be done through `ADD`/`REMOVE`)
- allow modifying scripts in `.singularity.d` (e.g., `runscript`, `99-environment.sh`)

**Comment by gmkurtzer** [comment]
We have to be very careful about differentiating between the functions of `import` and `bootstrap`. Import can not bootstrap, because on the backend it is just taking tar streams and throwing that into an image. It isn't making any modifications (however as @vsoch mentioned, we could modify the tarballs before or during the streaming). Bootstrapping is always the most flexible and easiest to customize, but that entire process requires root.

I may have muddied the lines of what is possible by figuring out how to import as non-root, but the processes are massively different on the backend and generally not compatible with each other.

Now going back to what @vsoch mentioned, we could modify the tarballs and/or tarstreams in flight. While that is possible, I don't know what that interface would look like, and because the backend mechanisms are not compatible between `import` and `bootstrap`, I don't want to do it via a definition file as that would confuse the process from the user's perspective.

**Comment by vsoch** [comment]
In my mind, `.singularity.d` is like the pilot cabin of the airplane. It's important for the planes workings, the pilots communicate things back to the passengers, but the passengers don't get to go inside. I don't think I like the idea of encouraging the user to stick his/her hands in there, and that includes adding custom scripts. A con - this addition would still require having some command line or text file source to identify the scripts to add, and then adding a file to the tar, and then the result is (still) a container that has files that shouldn't be there. A pro - it gives the user more flexibility. But actually, maybe that's a con. We have a very basic need - adding or removing content from an (already existing) tarball, and the question is how to best make that happen.

I agree with @gmkurtzer , now that I think of it, that we don't want to confuse bootstrap and import. Do you think it would be confusing to allow for an import also using an equivalent bootstrap file? Or should we have another interface? What we would basically be providing are tools for a user to edit a tarball. Arguably, given that the layers are local, the user could just do that him or herself. But that's kind of annoying. I (still) think we could have something that would look like:

```bash
singularity import image.img 
 #or
singularity import image.img spec://Singularity 
```

Where `Singularity` is the definition file, even with extra sections like `%post` and `%setup` that are ignored given a non sudo import. So the C parser would do something like:

- find runscript via the spec:// uri
- check if From is docker. If not, stop and tell user can't do that
- if docker, either parse %environment, %labels, %files sections and send to python with import, or send entire file to python for python to parse
- %setup and %post are ignored
- python parser does import, filters tarball, and writes metadata (labels, env) into same tarball
- sends content file back to C, import finishes same as now.

Instead of import with a spec:// uri, it also could be some custom flag like --filter file.txt that has simple commands like:

```bash
ADD /path/to/file.txt
REMOVE /path/in/docker
ADD /bla/bla/*
```
and of course the challenge would be defining things like regular expressions. The rule would be that only the tarball content can be modified, and nothing on the actual filesystem or already in the container. I would even say we can make this more general, instead of `--filter` do something like `--edit` or `--modify` or `--usercommand` and then allow for a single text file with a list of possible COMMAND KEY VALUE pairs/trios that specify customization that can be done. For example:

```bash
REMOVE /path/to/folder/*.txt
ENV KEY VALUE
LABEL Modified By Vanessa 
```

and then the C parser could hand that whole thing to python, and python would parse it. It would look very similar to a Dockerfile, and be obviously different from the bootstrap file.

**Comment by gmkurtzer** [comment]
I like your thinking on this, but I don't like the idea of having an import spec file as then it is still very much like bootstrap. Can it be done via command line args?

**Comment by vsoch** [comment]
Command line args would work, albeit be messy. It would be simple to have one or two things, like:

```bash
singularity import image.img docker://ubuntu:latest \
   --remove "/path/to/folder,/another/path/here.txt,regexp"
   --add "/path/to/file.txt"
   --label "Vanessa isadinosaur spaces? Weird characters? Extra quotes and commas?"
```
We could also allow multiple of the same command line argument, so the comma / spacing thing is a litle less weird, but then you would just have to parse that instead, lol. so like:

```bash
singularity import image.img docker://ubuntu:latest \
   --remove "/path/to/folder" \
   --remove "/another/path/here.txt" \
   --remove "regexp" \
   --add "/path/to/file.txt" \
   --label "Vanessa isadinosaur spaces? Weird characters? Extra quotes and commas?" 
```

Ewww.

**Comment by vsoch** [comment]
I guess Docker lets you do something like that. I could be convinced it's not fugly.

**Comment by gmkurtzer** [comment]
Oh wow... that is pretty bad. I would suggest then to just do it with bootstrap. :-P

**Comment by vsoch** [comment]
So you would be open to allowing for a bootstrap file to be used in a Non sudo context to add / remove files and specify environment and labels?

**Comment by gmkurtzer** [comment]
Nope. bootstrap's always need `sudo`. <runs>

**Comment by vsoch** [comment]
I guess @satra it's your turn to put forward some good ideas / arguments to convince @gmkurtzer, lol. :popcorn: :popcorn:

**Comment by gmkurtzer** [comment]
hahaha... Teamwork, I love it!

**Comment by satra** [comment]
i'm on it - but i'll need 24 hours to come up with lame excuses!

**Comment by vsoch** [comment]
lol, you got it! 

:popcorn:  *puts popcorn away for tomorrow* :popcorn:

**Comment by gmkurtzer** [comment]
uh-oh.... I'm preparing for the inundation of lots of brainstorming against me!

**Comment by satra** [comment]
alright i think this boils down to the intent more than what's possible and not. (similar to the obfuscation discussion on slack).

my use case:

fix something from dockerhub the lazy way. it doesn't work with singularity, so figure out the issue. a. save the runtime dir, b. fix the issues inside the runtime dir, and 3. run the modified runtime dir.
things that have been addressed already in singularity since i adopted this practice are:
- user bind points to non-existent locations in container
- conversion of environment variables from docker to singularity
- i think entrypoint is also now taken into account, but i haven't personally checked yet.

so that's great - it seems that every issues i've run into has been taken care of thus far. now the latest issue had to do with the r/w mode of files #571 which was fixed by #575 

so technically i don't need this anymore till i come up with a new use case! feel free to close this issue.

sorry @vsoch not much drama here! but you should just eat the 🍿 !

**Comment by vsoch** [comment]
:popcorn: !! :popcorn: !! :popcorn: !!

+1 entrypoint is parsed, unless you specify to IncludeCmd: yes (in bootstrap header) or define a custom runscript to override. For example, here we are running python latest:

```bash
$ singularity run docker://python
Docker image path: index.docker.io/library/python:latest
Cache folder set to /home/vanessa/.singularity/docker
Downloading layer sha256:6d827a3ef358f4fa21ef8251f95492e667da826653fd43641cef5a877dc03a70
Progress |========================================| 100.0% downloading layer  
Progress |========================================| 100.0% preparing layer  
Downloading layer sha256:2726297beaf19be957416750338c095ae15b94adc0e8c1306cebbf113f8b9a5c
Progress |========================================| 100.0% downloading layer  
Progress |========================================| 100.0% preparing layer  
Downloading layer sha256:7d27bd3d7fecb89d4028f4afa3ee866d2262c5105fc37f57aa82af918dc2f84c
Progress |========================================| 100.0% downloading layer  
Progress |========================================| 100.0% preparing layer  
Downloading layer sha256:44ae682c18a31909b5b2e1c0e95d4a05cdf032e983a0e8dc36cc329fc32b53cd
Progress |========================================| 100.0% downloading layer  
Progress |========================================| 100.0% preparing layer  
Downloading layer sha256:824bd01a76a3b27f2a3f1ed93100d5adde6e508babd2434c1b286602249a8e8f
Progress |========================================| 100.0% downloading layer  
Progress |========================================| 100.0% preparing layer  
Downloading layer sha256:68fe59875298c7f7a1c0682bee33645011e38c715f176c5c802a8ecd6b3e73c1
Progress |========================================| 100.0% downloading layer  
Progress |========================================| 100.0% preparing layer  
Downloading layer sha256:9ca1d7ae0c4bff87b01dabb6e7f35ef1d64146f90c8a665a33614f77400b137b
Progress |========================================| 100.0% downloading layer  
Progress |========================================| 100.0% preparing layer  
Importing: base Singularity environment
Exploding layer: sha256:6d827a3ef358f4fa21ef8251f95492e667da826653fd43641cef5a877dc03a70.tar.gz
Exploding layer: sha256:2726297beaf19be957416750338c095ae15b94adc0e8c1306cebbf113f8b9a5c.tar.gz
Exploding layer: sha256:7d27bd3d7fecb89d4028f4afa3ee866d2262c5105fc37f57aa82af918dc2f84c.tar.gz
Exploding layer: sha256:44ae682c18a31909b5b2e1c0e95d4a05cdf032e983a0e8dc36cc329fc32b53cd.tar.gz
Exploding layer: sha256:824bd01a76a3b27f2a3f1ed93100d5adde6e508babd2434c1b286602249a8e8f.tar.gz
Exploding layer: sha256:68fe59875298c7f7a1c0682bee33645011e38c715f176c5c802a8ecd6b3e73c1.tar.gz
Exploding layer: sha256:9ca1d7ae0c4bff87b01dabb6e7f35ef1d64146f90c8a665a33614f77400b137b.tar.gz
Exploding layer: sha256:935565c46855dd50a3ef69a78deccb753acbdf41436b0c2b5a5d966eac6d95ed.tar.gz
Python 3.6.1 (default, Mar 23 2017, 02:34:11) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
and it goes right into the python shell! We can lazily look at the runscript, which isn't the docker entrypoint, but [the cmd](https://github.com/docker-library/python/blob/32e920eb13714a9aeff2e016fb467901222d17b5/3.6/Dockerfile#L84): 

```python
>>> import os
>>> os.listdir('/.singularity.d/env')
['01-base.sh', '10-docker.sh']
>>> os.listdir('/.singularity.d')
['env', 'labels.json', 'actions', 'runscript']
>>> with open('/.singularity.d/runscript') as filey:
...      content=filey.readlines()
... 
>>> content
['#!/bin/sh\n', '\n', 'exec python3 "$@"']
```
and this is because there is no entrypoint, so it uses the cmd second.

@gmkurtzer - how about getting rid of the extra print statement about downloading? It seems redundant now with the progress bar. Ok, closing issue! Thanks for the :popcorn: @satra !

**Comment by gmkurtzer** [comment]
You mean the:

```
Downloading layer sha256:6d827a3ef358f4fa21ef8251f95492e667da826653fd43641cef5a877dc03a70`
```

If so, I would say yes, and let's use a small version of that (if we can fit it reasonably) in the progress bar output? Maybe something like:

```
[1/7] Download |========================================| 100.0% Layer: 6d827a
[1/7] Prepare    |========================================| 100.0% Layer: 6d827a
[2/7] Download |========================================| 100.0% Layer: 272629
[2/7] Prepare    |========================================| 100.0% Layer: 272629
...
```

I think that is less then 80 chars wide, but I'll leave the design up to you. lol

**Comment by vsoch** [comment]
Hmm let me see what I can do - of the bat I don't like how it's unever at the beginning :)

**Comment by gmkurtzer** [comment]
Oh, it is only uneven because the fonts are not fixed width and I may not have hit spacebar right number of times. lol

But, yeah,... I was assuming you could make it much more better. ;)

**Comment by vsoch** [comment]
ok, back to working on this! Had a erm, slight delay, lol
