### ISSUE TITLE
Feature: NVIDIA_VISIBLE_DEVICES support

### ISSUE THREAD

**Issue by dtrudg** [apptainer/singularity#5829]
Masking / limiting use of NVIDIA GPUs in containers is via the NVIDIA_VISIBLE_DEVICES variable in the OCI world. Singularity binds a complete dev tree by default, and all GPUs within a --contain-ed dev tree, so GPU limitation is limited to application specific config and/or CUDA_VISIBLE_DEVICES usage, which has limitations and is not respected nicely by all software. Work to respect the NVIDIA_VISIBLE_DEVICES environment configuration when creating a --contain-ed /dev tree, such that GPU limitations and MIG are supported in a manner that is consistent with OCI runtimes. Investigate, and implement if possible, device masking in uncontained mode run with --nv

Sylabs roadmap item: https://docs.google.com/document/d/1mEjRmwOfFXiz4U5uPQ6paa-h3jDgMeGoxM5PPs6r8SI

**Comment by andyneff** [comment]
Is there any current work accomplish the equivalent to this? In my case I can only use singularity 2.6.1 or 3.5.3

**Comment by dtrudg** [comment]
No, there's no real straightforward way to mimic NVIDIA_VISIBLE_DEVICES docker behaviour - currently you need to use `CUDA_VISIBLE_DEVICES` or options specific to the program you are using. Some workload managers / schedulers may support setting up virtual MIG devices also.

Please note that Singularity 2.6.1 and 3.5.3 are not supported, and are subject to security issues fixed in newer versions. The new features will only be added to 3.8.

**Comment by dtrudg** [comment]
Having done a bunch of investigation and playing around on this now I think the only sensible approach is to call out to `nvidia-container-cli` for our binds and cgroups device limitation stuff, as long as it doesn't disrupt anything else Singularity is doing.

Manually handling the setup in Singularity alone would involve a lot of looking at `nvidia-smi` output, and/or other info from `/sys` to understand what we need to do, in terms of how the env var ID/UUIDs map to device IDs for access restriction.

The main concern, though, is a transition from `/proc/driver/nvidia/capababilities` based access control onto a '/dev based approach'. This is ongoing and driver versions in use will straddle the approaches:

https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#device-nodes

> The current CUDA 11/R450 GA (Linux driver 450.51.06) supports both mechanisms, but going forward the /dev based interface is the preferred method and the /proc based interface is deprecated. For now, users can choose the desired interface by using the nv_cap_enable_devfs parameter on the nvidia.ko kernel module

It's not feasible for us to write code for both of these models, and maintain / test it well. CUDA support is a quicker moving target these days, so adopting the upstream tooling seems to make sense.

**Comment by dtrudg** [comment]
Regrettably I'm going to remove this from the 3.8 milestone. 

Due to events outside of work I have had less time that usual over the past week, and that'll continue for a bit. I was hoping to discuss the feature in the community dev meeting, but I couldn't attend.

I'm convinced that using `nvidia-container-cli` here is the right way forward, given the complexities with the transition from `/proc` to `/dev` GPU driver control, and general pace of feature addition in the NVIDIA driver stack as new cards come out with new capabilities. Things are more complex now than when this work was first considered. 

The POC in #5928  does use `nvidia-container-cli` to setup a minimally operational GPU environment in the container. My aim had been to work this up further and propose for 3.8 that it could be an experimental flag, rather than a full battle-tested feature.

The approach employed requires running `nvidia-container-cli` from the Singularity RPC server. The RPC server has a limited capability set. To run `nvidia-container-cli` the bounding set of capabilities has to be opened up substantially. I note there is an aim to rework capability handling in #5314 and it's likely that large changes to bounds of capabilities should be considered in that regard.

I think there is a much better understanding now of what is required, and we have a good route to ensure that a plan to bring in this functionality in a well tested, and sustainably maintained manner can be developed and followed for a future release. This will also need discussion around maintaining / deprecating the existing non nvidia-container-cli method.

**Comment by carterpeel** [comment]
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by andyneff** [comment]
@carterpeel This is still a relevant issue

**Comment by andyneff** [comment]
Still a relevant issue

**Comment by DrDaveD** [comment]
The imported sylabs pr for this is now in #6231, but it invokes the external command nvidia-container-cli with elevated privileges and some of the committers think that's too risky.  So it appears at this point that it is unlikely to be accepted for version 3.9, at least without modification.

I have been told that this works also without setuid-root and instead with unprivileged user namespaces.  If that's the case, perhaps a compromise would be to only support it with the latter.

**Comment by gmkurtzer** [comment]
I'm not familiar with this myself, but if the `nvidia-container-cli` can run without privileges, then it should be possible to move it to the unprivileged portion of the code. If not, then Singularity has no business executing any external shell code or library with enhanced capabilities.

I would prefer this feature being something that the scheduler normally would/should manage and expose via an environment variable, but if there is a strong interest in doing this directly, we can certainly come up with a less risky way to implement it.

**Comment by DrDaveD** [comment]
I have verified that `nvidia-container-cli` can run with unprivileged singularity (including using the `--writable` option as it is documented to require when running unprivileged).  What is not possible, I believe, is to use it with the unprivileged portion of the code while running with privileged singularity, for this reason:  when singularity is run privileged, the system files are owned by root rather than the user.  The `nvidia-container-cli` command does a lot of manipulation in /lib64, creating symlinks and doing bind mounts.  Even with the `--writable-tmpfs` option, privileged singularity does not allow writing into /lib64.  If there were a way to use unprivileged user namespaces as I requested in #2727 even while running privileged I think this could work.

Since there is not currently a way to use unprivileged user namespaces while running privileged, I propose to simply disable support for this feature when singularity is run privileged, for now.  @gmkurtzer @cclerget do you agree?

**Comment by DrDaveD** [comment]
#6231 is merged and the answer to this.  It only works while running unprivileged.
